IgorRozani/filosofunk

app.js
index.html

frazes randomicas agora nao repetem e pagina nao recarrega a cada
declamação 😎😎🤓🤓

melhoramentos

---

poesias.json

adicionada nova poesia

---

poesias.json

https://www.youtube.com/watch?v=oZpWVwpRS9g

Nova poesia adicionada

---

poesias.json

https://www.youtube.com/watch?time_continue=12&v=Sigzf7-WW5M 
https://www.youtube.com/watch?v=TPgL-GporMw

add pai de todos Mr. Catra

---

poesias.json

Youtube: https://www.youtube.com/watch?v=N4Q4j1oSdUU

Trecho da música Cheio de Sal do MC Gorilla

---

poesias.json

https://www.youtube.com/watch?v=jjdTRQ_CiFA

Oh Quem Voltou - Dani Russo adicionado

---

poesias.json

https://www.youtube.com/watch?v=D5FZs3OJzR0

Adrezinho Shock adicionado

---

poesias.json

Segue na ordem de inseração:
Roça Roça 1 - Mc Brinquedo: https://www.youtube.com/watch?v=z-EIyVPSlf8
Dom Dom Dom - Mc Pedrinho & Mc Magrinho: https://www.youtube.com/watch?v=EE0Zcs0yBoQ
Harry Porra e a Bruxinha Rabuda - Mc Maha: https://www.youtube.com/watch?v=5jg9hFPhgSs

Adiciona novas poesias

---

poesias.json

https://www.youtube.com/watch?v=byXfKMEmVZc

Mc kekeu adicionado

---

poesias.json

https://www.youtube.com/watch?v=_P7S2lKif-A

Add bumbum tam tam

---

poesias.json

Link da poesia contemporânea: https://www.youtube.com/watch?v=vA9KRZPxrN0

Adicionada poesia do Mc Livinho

---

poesias.json

Link para a musica https://www.youtube.com/watch?v=dw4UWMvw7iA

Os caras do momento - MC Nego do Borel

---

poesias.json

A melhor poetiza do Brasil e coloquei umas vírgulas que esqueceram.

Nova frase e ajuste das vírgulas

---

poesias.json

mais funks: http://www.funk.blog.br/funks-engracados

adiciona duas estrofes

---

poesias.json

Parabéns pelo projeto ! Ajudei com 3 poesias novas 👍

Adicionado 3 poesias

---

css/site.css
index.html
js/app.js

Creie uma sugestão para play/pause das musicas nas frases #40

issue #40 - opção de silenciar musica

---

poesias.json

Adicionando Bonde do Tigrão

---

poesias.json

Added "Ela é bandida" and "Teoria da branca de neve" by Mc mayara

Add poetry by Mc Mayara

---

poesias.json

Adicionando Ela é  :top:

---

poesias.json

poesia do mc brinquedo e do mc marcinho

minha contribuição

---

poesias.json

Mais músicas

---

poesias.json

Mc Timbu - Ela queria ter 2 buceta

---

poesias.json

Este commit adiciona uma das maiores e melhores poesias de 2013 #hacktoberfest 😸

Adiciona a poesia do Mc Tarapi

---

poesias.json

Update with new poetry and fix variables on previous stretch

Update poesias.json with Amor de Verdade poetry

---

poesias.json

Edited file to add one more song to collection. 
:octocat:

Added lyrics

---

poesias.json

Added poesia Cara Bacana

---

poesias.json

As seguintes frases foram adicionadas:
"Pra ser fiel, só a torcida da Gaviões"
"Eu decifro seu corpo sem ter manual, vem que vem"
"Se apaixonar pra quê? Pra depois tu ficar sofrendo!"
"Ô, Xanaina, vem rebolar na linguiça"

 Frases de Mc Daleste, Biel, MC Kapela e Mc Lan adicionadas

---

poesias.json

Corrige também algumas vírgulas que estavam faltando e uma indentação errada

Adiciona poesia do Mc Lan e Mc Gw

---

poesias.json

#10 Adicionada nova poesia tirada da música Engole o Choro do MC Kapela

Nova poesia do MC Kapela

---

poesias.json

#10  Nova poesia da música Pode Se Soltar de Jerry Smith adicionada

Nova poesia de Jerry Smith

---

poesias.json

#10  Adicionada nova poesia da música Pode Vim Que Tem do MC Bruxo

Adicionada nova poesia do MC Bruxo

---

poesias.json

#10  Adicionada poesia da música Ostentar Superação do MC João

Nova poesia do MC João adicionada

---

poesias.json

- Até agora não descobri o que é lombrado mas achei poesia pura

Atualização do poesias.json Surtada

---

poesias.json

Também foi corrigido estrutura do arquivo JSON, tinha uma chave a mais que estava quebrando a apalicação.

Adicionado poesia Namorar nao da da, de Kevin o Chris e corrigindo estrutura do arquivo JSON

---

poesias.json

Inserção de poesia

---

poesias.json

Formatação adicional no poesia.json

Mc Kevin - Sniper

---

poesias.json

Adiciona um trecho da poesia "Vamos Pra Gaiola"
Signed-off-by: Leonardo Lana <leolanavo@gmail.com>

Add 'Vamos Pra Gaiola' quote

---

poesias.json

"Em tempos de crise eles tão se comportando como se nada tivesse aumentado, como se o Money tivesse girando" - Século XXI; MC Davi e MC Hariel

Poesia Século XXI

---

poesias.json

Add 4m no Toque Mc Pedrinho

---

poesias.json

Treme, Treme - Mc Loma e as Gêmeas Lacração
Quer mais? - Pocah e Mc Mirella
Não sou obrigada - Pocah
Issue #10

Mais três sábias citações de artistas contemporâneas

---

poesias.json

Insere a grande obra do mestre Mc Niel juntamente com FP do Trem Bala.
Uma grande poesia do século XXI, na qual diz que até foi bom encontrar uma pessoa, porém é a esbórnia que ela ama.

Insere FP do Bullet Train

---

poesias.json

#10  Adicionada nova poesia da música Tenebrosa do MC Livinho

Adicionada nova poesia de MC Livinho

---

poesias.json

#10  Adicionada nova poesia da música Nem Guindaste de Jottapê e Mila.

Adicionada nova poesia de Jottapê e Mila

---

poesias.json

#10 Adicionada nova poesia da música Qual Bumbum Mais Bate? de Os cretinos

Adicionada nova poesia de Os cretinos

---

poesias.json

#10 Adicionada nova poesia da música Sente O Contraste do MC Neguinho do Kaxeta

Adicionada nova poesia de MC Neguinho do Kaxeta

---

js/app.js
poesias.json

E add também um '-' antes do nome do autor da musica, para deixar parecendo citação...

add música 'vai luan' 

---

poesias.json

Projeto muiiito massa parabéns!

Adicionando funk emo - mc maha

---

poesias.json

'Água coca latão água coca latããão, pra gringo é mais carooo'

feat: Adicionado melhor poesia dos ultimos tempos Mc Negão da BL

---

poesias.json

Olá, muito bom o projeto!
Contribui adicionando novas frases e 2 Mc's que ainda não tinha, vou divulgar para meus amigos e sempre que possivel colaborando mais com o projeto. Estou estudando desenvolvimento web e pretendo poder agregar mais futuramente.

adicionando-novos-mcs-e-frases

---

poesias.json

adicionei mais uma poesia para a lista

Add Mc Niack - Oh Juliana

---

poesias.json

musica baile de favela

---

poesias.json

feat: add poesia tava cagado

---

poesias.json

adicionando musica da familia brasileira meu namorado é mo otario

adicionando meu namorado é mo otario

---

poesias.json

Adicionando essa bela obra de arte ao repositório

feat: Sai fora nunca nem vi

---

poesias.json

feat: Add poesia Cheio de novinha querendo me dar

---

poesias.json

Adicionado Oh Juliana - Mc Niack

feat: Adicionado Oh Juliana - Mc Niack

---

poesias.json

Add Eu Kimetsu No Seu Rayba - MC Maha

feat: add meu funkao

---

poesias.json

Adicionado dança créu ao arquivo poesias.json
#10

Add dança créu

---

poesias.json

"Então martela, martela, martela o martelão."
- Tigrão, Bonde do

Add Cerol na Mao of Bonde do Tigrao

---

poesias.json

Adicionado MC Gordão - Permissão de Deus.

Adicionado MC Gordão

---

poesias.json

Add poesia:  Mc G15 - Deu onda e Dennis & Kevinho - Se Ferrou

feat: add 2 poesias

---

poesias.json

melhor poesia: mc brisola, whisky cama box e um sexo bolado.

whisky cama box

---

poesias.json

Salve mano, 
Maneiro o rep, espero que goste da contribuição.
Abs,
Beatriz

dona maria a sua filha ta bem (#230)

---

poesias.json

Boa noite!
Venho contribuir com esta bela poesia.
Abraço!!

Add poesia Ela Vem (#231)

---

poesias.json

Adicionei mais dois mcs que não tinha(guime e rodolfinho) e três musicas.

Adicionando Mc Guime e Mc Rodolfinho

---

poesias.json

Add poesia To Voando Alto

---

poesias.json

Add 2 pieces of the music "MC não é bandido"

added 2 pieces of the music 'MC Não é bandido'

---

poesias.json

feature: Adiciona frase

---

poesias.json

adicionando mais tres novas musicas

adicionando tres novas musicas

---

poesias.json

Mais uma pequena contribuição para o incrivel projeto

adicionando novas musicas

---

poesias.json

máquina de sexo - chátuba de mesquita

musica adicionada

---

poesias.json

Incluindo poesia O Grave Bater do MC Kevinho

---

poesias.json

Song: [Mc Levin - Vê Se Pode](https://www.youtube.com/watch?v=xxAYOQV-6WQ)

feat: add mc levin song

---

poesias.json

#10 Nova poesia do hit do ídolos de 2014.

Nova Poesia do MC Duplex

---

poesias.json

Também corrigi a formatação da última poesia adicionada.

Adicionada estrofe do Passinho do Japonês

---

poesias.json

Adicionei uma estrofe da música Fazer Falta do MC Livinho e corrigi a indentação da parte final do código, algumas estrofes estavam fora do padrão.

Adicionada estrofe da música Fazer Falta

---

poesias.json

Adicionei uma estro da música Sexo No Camarote do MC Brisola.

Adicionada estrofe da música Sexo No Camarote

---

Site/js/app.js

Função de carregar música atualizada, a partir de agora as músicas podem ser adicionadas com o esquema:
{
"estrofe": "Sou foda",
"poesia": "Sou Foda",
"poeta": "Avassaladores",
"youtubeId": "RIBkK5X_3mo",
"startTime": "5",
**"endTime": "6"**
}

function carregarMusica com endTime adicionado

---

poesias.json

Primeira vez contribuindo com projetos open Sources para o hacktoberfest, espero que esse pull seja aceito ;)

Adiciona nova poesia de Mc Carol

---

poesias.json

Adicionei uma estro da música Anota aí do grande pensador contemporâneo Mc Lipe

Adicionada estrofe da música Anota aí

---

poesias.json

Adicionando música Partiu do Mc Kekel, grande filósofo contemporâneo

Adicionando música Partiu

---

poesias.json

Adicionando os clássicos Cheio de Ódio do poeta Menor do Chapa e Dessa Vez da poetiza Mc Sabrina.

Add Dessa Vez and Cheio de Ódio

---

poesias.json

Minha contribuição com uma frase que achei muito bacana!

Added Pensamentos trancados

---

poesias.json

Adicionei esse trecho da música [GIRO LOUCO - Mc PH](https://www.youtube.com/watch?v=qxpYri5vHU4)
1. Quero muito porque vim do pouco, minha ambição é mais que o topo

add Giro Louco - Mc PH

---

poesias.json

Adicionei esses dois trechos da música [Tô Tranquila - Bivolt](https://www.youtube.com/watch?v=X53QOT_BaG4)
1. Se não gosta da sua vida eu não posso fazer nada se a feiura no espelho é algo que te maltrata
2. Bonita, gostosa, me banco, eu sou foda!
💃

add Tô Tranquila - Bivolt

---

poesias.json

Adicionando música da nova pensadora contemporânea: Mc Melody, Fale de mim.

Adicionando música: Fale de mim

---

poesias.json

Adição de três novas frases para o Filosofunk

Adição de novas frases

---

poesias.json

poesias de MC Livinho, Anitta (feat. MC Guimê) e Anitta!

adiciona 3 novas músicas
